version: "2"
services:
  db:
    image: mysql:5.6
#    container_name: test-mysql
#    restart: always
#    ports:
#      - "3306:3306"
    volumes:
      - ./_db:/var/lib/mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: work_attendance
    networks:
      - net-mysql

  db-admin:
    image: phpmyadmin/phpmyadmin:4.6
    container_name: db-admin
    ports:
      - "8082:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: work_attendance
      PMA_HOST: test-mysql
    networks:
      - net-mysql

networks:
  net-mysql:
    external: true

