# Generated by Django 2.1.1 on 2018-09-17 16:26

import apps.django_account.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=apps.django_account.helper.generate_id, max_length=40, primary_key=True, serialize=False)),
                ('create_time', models.IntegerField(verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=40, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('nick_name', models.CharField(default='', max_length=40, verbose_name='花名')),
                ('class_name', models.CharField(default='', max_length=40, verbose_name='班级名称')),
                ('mobile', models.CharField(default='', max_length=20, null=True, verbose_name='手机号')),
                ('qq', models.CharField(default='', max_length=20, null=True, verbose_name='QQ')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='MemberUserAccount',
            fields=[
                ('id', models.CharField(default=apps.django_account.helper.generate_id, max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=8)),
                ('create_time', models.IntegerField(default=apps.django_account.helper.get_time)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
